### ISSUE TITLE
Discuss on trade-offs and key architectural decisions

### ISSUE THREAD

**Issue by dragonfist453** [Soundscape-Project-UCL/Soundscape#13]

**Comment by nextedoff** [comment]
Only has comparison of cross platform vs native Android.
Still requires a final version of architecture to be able to analyse architectural trade offs. We currently do not really have any sacrifices.

**Comment by FlickerSoul** [comment]
Should we close this and open up a new one for refining the sections?

**Comment by dragonfist453** [comment]
Yep

**Comment by FlickerSoul** [comment]
Close in favoring #28
