### ISSUE TITLE
Build 54 - crash

### ISSUE THREAD

**Issue by jchudge** [Soundscape-Project-UCL/Soundscape#211]
Overall, this is very functional and data loading and ordering etc working well. 
however, I experienced the following 2 issues:
- I could not get the audio beacon to identify when i was facing towards the nearby Tesco Express
- On selecting Big Ben from Search, the app crashed when I pressed the Start Audio beacon button.

**Comment by FlickerSoul** [comment]
This seems outdated and will be closed. New issues are welcomed :)
