### ISSUE TITLE
Sound files and their access implementation

### ISSUE THREAD

**Issue by nextedoff** [Soundscape-Project-UCL/Soundscape#42]
Gather the beacon sounds and main audio files from the original Soundscape project. Create a way to safely access them in the application.

**Comment by FlickerSoul** [comment]
@nextedoff Please check out the commit 76b9743 and commit 3bb585c. Android provides ways to access assets with asset IDs. The first commit has an set of enums categorizing the audio beacons asset IDs. When the IDs are submitted to the system APIs (like media players and getters), they can access the files, which is demonstrated in the second commit.

**Comment by FlickerSoul** [comment]
The features are fully implemented and this issue will be closed. 

Note that `KClass` could cause performance degeneration. See https://slack-chats.kotlinlang.org/t/464419/kotlin-reflection-on-the-jvm-seems-to-be-100x-slower-than-ja and https://youtrack.jetbrains.com/issue/KT-32198. Another issue will be opened if such performance improvement matters.
